### ISSUE TITLE
Dragging while scrolling moves the cursor without the selected element

### ISSUE THREAD

**Issue by qhga** [dominiksta/wournal#6]
Expected behaviour:
Cursor should be anchored to the selected item while dragging a selected item, even while scrolling.

Actual behaviour:
While scrolling, the element stays where it was even though it is dragged by the cursor which moved according to the scroll position.
![image](https://github.com/dominiksta/wournal/assets/15987853/581badb4-b279-4478-a359-9bc84bdfda22)

Wournal version: 0.0.4

**Comment by dominiksta** [comment]
Thanks for the report, fixed in 6d75528 :+1:
